[package]
name = "cosmic-text-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cosmic-text = {rev = "a03ec6b75f0ea8fd6264d6cd05afcec3c2213f8f", git = "https://github.com/pop-os/cosmic-text", features = ["no_std"]}
bitflags = "2.5.0"