[package]
name = "cosmic-text-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cosmic-text = {rev = "8bb45d7aca5b4a109924f3162d670297b6bd4a19", git = "https://github.com/pop-os/cosmic-text"}